site_name: PowerSMPP Documentation
site_url: https://powersmpp.com         

theme:
  name: material
  features:
#    - navigation.expand
#    - navigation.tabs
#    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.code.copy
    - content.action.edit
  font:
    text: Roboto
    code: Red Hat Mono
  logo: assets/powersmpp.png
  favicon: assets/pslogo.png
  language: en 
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: cyan
      accent: cyan
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: white
      accent: deep orange

INHERIT: ./nav.yml    

